# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countGlobal', models.IntegerField(default=0)),
            ],
        ),
    ]
